<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Rostok.Controls</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rostok.Core\Rostok.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\*.ttf" />
    <Resource Include="Assets\*.png" />
  </ItemGroup>

</Project>
